POST http://192.168.39.209:32094/realms/eselwer/protocol/openid-connect/token
content-type: application/x-www-form-urlencoded

grant_type=refresh_token
&client_id=eselwer-admin
&client_secret=MpDq1EwelMh4FJB4h37mlvvYQiR6o5Lb
&refresh_token=eyJhbGciOiJIUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICI1ODQzMzkxNS1lNGUzLTRiM2YtYWRjYS1mN2VjZTFiOTU3ZDMifQ.eyJleHAiOjE2ODU3NDUzNTUsImlhdCI6MTY4NTMxMzM1NSwianRpIjoiOTZkZDdmZjUtNTRiOS00MDc5LWI5YTUtMzEzYjhjYTVlZjIzIiwiaXNzIjoiaHR0cDovLzE5Mi4xNjguMzkuMTU6MzIzMjEvcmVhbG1zL2VzZWx3ZXIiLCJhdWQiOiJodHRwOi8vMTkyLjE2OC4zOS4xNTozMjMyMS9yZWFsbXMvZXNlbHdlciIsInN1YiI6ImY1ZjQzODUwLWJkZGItNGQ4OC04OTcyLTgwNDJlNmNmYjMxZSIsInR5cCI6IlJlZnJlc2giLCJhenAiOiJlc2Vsd2VyLWFkbWluIiwic2Vzc2lvbl9zdGF0ZSI6ImFjYjYwYTljLWEyYjItNGE0ZC1hZjMxLThmZDc5ZDBlMzU3YiIsInNjb3BlIjoib3BlbmlkIHByb2ZpbGUgZW1haWwiLCJzaWQiOiJhY2I2MGE5Yy1hMmIyLTRhNGQtYWYzMS04ZmQ3OWQwZTM1N2IifQ.wRiuMJpbI74VK5q9RcfOxgMeXxOW48dcRjGWOlXsDzE

