POST http://192.168.39.209:31801/realms/feriaz/protocol/openid-connect/token
content-type: application/x-www-form-urlencoded

grant_type=client_credentials
&client_id=feriaz-portal
&client_secret=PD09DGKYdKKdfddi3t0F1stzqeku1wnF
&scope=roles

