POST http://192.168.39.209:30427/realms/eselwer/protocol/openid-connect/token
content-type: application/x-www-form-urlencoded

grant_type=password
&client_id=eselwer-admin
&client_secret=TiKbbV64bkGqW7d3hmsFHPCqf1nqiVtV
&username=110d5fab-7c8a-4307-9323-fa0fec39fbe6
&password=teste
&scope=roles

