POST http://localhost:8885/authentication/v1/identifications/token
content-type: application/json

{
    "grant_type": "client_credentials",
    "client_id": "feriaz-portal",
    "client_secret": "PD09DGKYdKKdfddi3t0F1stzqeku1wnF",
    "scope": "roles openid"

}
