POST http://poc-eselwer.sytes.net:9777/authentication/v1/identifications/token
content-type: application/json

{
    "grant_type": "password",
    "client_id": "eselwer-admin",
    "client_secret": "MpDq1EwelMh4FJB4h37mlvvYQiR6o5Lb",
    "username": "desenvolvedor",
    "password": "teste",
    "scope": "roles email openid"

}


