POST http://192.168.39.209:30941/authentication/v1/identifications/token
content-type: application/json

{
    "grant_type": "password",
    "client_id": "feriaz-portal",
    "client_secret": "9AkTo7IxVmIfmgUvCWjEskjPGN4JzwjN",
    "username": "admin-api",
    "password": "api-access",
    "scope": "roles email openid"

}


