apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: feriaz-app-env
  labels:
    app: account-app-deployment

  name: account-application
  annotations:
    type: app
    domain: account
    business: Users
    prometheus.io/scrape: "true"
    prometheus.io/path: "/metrics"
    prometheus.io/port: "8080"

spec:
  selector:
    matchLabels:
      app: account-app
  template:
    metadata:
      labels:
        app: account-app
        version: v1
    spec:
      containers:
          - name: account-application-container
            image: srochg/account:0.0.9
            resources:
              limits:
                cpu: "1"
                memory: "1Gi"
              requests:
                cpu: "0.5"
                memory: "512Mi"
            env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: SECRET_POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: SECRET_POSTGRES_PASSWORD
            - name: RABBIT_USER_ENV
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: SECRET_RABBIT_USER
            - name: RABBIT_PWD_ENV
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: SECRET_RABBIT_PWD
            envFrom:
              - configMapRef:
                  name: account-configmap
            imagePullPolicy: Always
            ports:
              - containerPort: 8080
            readinessProbe:
              httpGet:
                path: /_app-state/health
                port: 8080
              initialDelaySeconds: 20
              periodSeconds: 10
            startupProbe:
              httpGet:
                path: /_app-state/health
                port: 8080
              periodSeconds: 10
              failureThreshold: 30
              successThreshold: 1

            livenessProbe:
              httpGet:
                path: /_app-state/health #/realms/master
                port: 8080

              initialDelaySeconds: 30
              periodSeconds: 10
              failureThreshold: 5
              timeoutSeconds: 5
              successThreshold: 1
              terminationGracePeriodSeconds: 30
      restartPolicy: Always
