apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  namespace: feriaz-app-env
  name: search-domain-service-hpa
  annotations:
    type: app
    domain: search-domain
    business: Users
    prometheus.io/scrape: "true"
    prometheus.io/path: "/metrics"
    prometheus.io/port: "8080"

spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: search-domain-application
  minReplicas: 2
  maxReplicas: 4
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 98
          
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 90
