apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: feriaz-app-env
  labels:
    app: search-domain-app-deployment

  name: search-domain-application
  annotations:
    type: app
    domain: search-domain
    business: Users
    prometheus.io/scrape: "true"
    prometheus.io/path: "/metrics"
    prometheus.io/port: "8080"

spec:
  selector:
    matchLabels:
      app: search-domain-app
  template:
    metadata:
      labels:
        app: search-domain-app
        version: v1
    spec:
      containers:
          - name: search-domain-application-container
            image: srochg/search-domain:0.0.7
            resources:
              limits:
                cpu: "200m"
                memory: "1Gi"
              requests:
                cpu: "100m"
                memory: "512Mi"            
            envFrom:
              - configMapRef:
                  name: search-domail-configmap
            imagePullPolicy: Always
            ports:
              - containerPort: 8080
            readinessProbe:
              httpGet:
                path: /_app-state/health
                port: 8080
              initialDelaySeconds: 20
              periodSeconds: 10
            startupProbe:
              httpGet:
                path: /_app-state/health
                port: 8080
              periodSeconds: 10
              failureThreshold: 30
              successThreshold: 1

            livenessProbe:
              httpGet:
                path: /_app-state/health #/realms/master
                port: 8080

              initialDelaySeconds: 30
              periodSeconds: 10
              failureThreshold: 5
              timeoutSeconds: 5
              successThreshold: 1
              terminationGracePeriodSeconds: 30
      restartPolicy: Always
