apiVersion: v1
kind: Service
metadata:
  namespace: feriaz-app-env 
  labels:
    app: search-domain-app    
  name: search-domain-service
  annotations:
    type: service
    domain: search-domain
    business: Users
    prometheus.io/scrape: "true"
    prometheus.io/path: "/metrics"
    prometheus.io/port: "8080"

  
spec:
  type: ClusterIP
  selector:
    app: search-domain-app
  ports:
    - name: http-porta-web
      protocol: TCP
      port: 8080
      targetPort: 8080  
  sessionAffinity: "ClientIP"
