apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: feriaz-app-env
  labels:
    app: auth-server-app-deployment

  name: auth-server-application
  annotations:
    type: app
    domain: auth-server
    business: Security
    prometheus.io/scrape: "true"
    prometheus.io/path: "/metrics"
    prometheus.io/port: "8080"

spec:
  selector:
    matchLabels:
      app: auth-server-app
  template:
    metadata:
      labels:
        app: auth-server-app
        version: v1
    spec:
      containers:
          - name: auth-server-application-container
            image: srochg/auth-server:0.0.32
            resources:
              limits:
                cpu: "200m"
                memory: "1Gi"
              requests:
                cpu: "100m"
                memory: "512Mi"            
            env:
            - name: APP_CREDENTIAL_ID
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: SECRET_KEYCLOAK_APP_CREDENTIAL_ID
            - name: APP_CREDENTIAL_SECRET
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: SECRET_KEYCLOAK_APP_CREDENTIAL_SECRET
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: SECRET_POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: SECRET_POSTGRES_PASSWORD
            - name: RABBIT_USER_ENV
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: SECRET_RABBIT_USER
            - name: RABBIT_PWD_ENV
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: SECRET_RABBIT_PWD
            - name: ADM_KEYCLOAK_CLI_SECRET
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: PROFILE_ADM_KEYCLOAK_CLI_SECRET
            - name: ADM_KEYCLOAK_SECRET
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: PROFILE_ADM_KEYCLOAK_SECRET
            - name: ADM_KEYCLOAK_USER
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: PROFILE_ADM_KEYCLOAK_USER
            - name: ADM_KEYCLOAK_PWD
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: PROFILE_ADM_KEYCLOAK_PWD
            envFrom:
              - configMapRef:
                  name: auth-base-configmap
            imagePullPolicy: Always
            ports:
              - containerPort: 8080
            readinessProbe:
              httpGet:
                path: /_app-state/health
                port: 8080
              initialDelaySeconds: 20
              periodSeconds: 10
            startupProbe:
              httpGet:
                path: /_app-state/health
                port: 8080
              periodSeconds: 10
              failureThreshold: 30
              successThreshold: 1

            livenessProbe:
              httpGet:
                path: /_app-state/health 
                port: 8080

              initialDelaySeconds: 30
              periodSeconds: 10
              failureThreshold: 5
              timeoutSeconds: 5
              successThreshold: 1
              terminationGracePeriodSeconds: 30
      restartPolicy: Always
