apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  namespace: feriaz-app-env
  name: auth-server-service-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: auth-server-application
  minReplicas: 2
  maxReplicas: 4
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 98
          
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 90
