apiVersion: v1
kind: Service
metadata:
  namespace: feriaz-app-env 
  labels:
    app: gateway-app    
    
  name: gateway-service
  annotations:
    type: service
    domain: Gateway
    business: Gateway
    prometheus.io/scrape: "true"
    prometheus.io/path: "/metrics"
    prometheus.io/port: "8080"

  
spec:
  type: LoadBalancer
  selector:
    app: gateway-app
  ports:
    - name: http-porta-web
      protocol: TCP
      port: 8080
      targetPort: 8080  
  sessionAffinity: "ClientIP"
