apiVersion: v1
kind: ConfigMap
metadata:
  namespace: feriaz-app-env
  name: auth-base-configmap
data:  
  PORT: '8080'
  PROFILE: prod
  KEYCLOAK_ADDRESS: 'feriaz-dev.ddns.net:9877'
  KEYCLOAK_HELM: feriaz
  KEYCLOAK_APP_CREDENTIAL_ID: ${APP_CREDENTIAL_ID}
  KEYCLOAK_APP_CREDENTIAL_SECRET: ${APP_CREDENTIAL_SECRET}
  PROFILE_ADM_CLI_ID: ${ADM_KEYCLOAK_CLI_SECRET}
  PROFILE_ADM_SECRET: ${ADM_KEYCLOAK_SECRET}
  PROFILE_ADM_USER: ${ADM_KEYCLOAK_USER}
  PROFILE_ADM_PWD  : ${ADM_KEYCLOAK_PWD}
  DB_ADDR: '192.168.15.103'  
  DB_USER: ${POSTGRES_USER}
  DB_PASSWORD: ${POSTGRES_PASSWORD}  
  DB_JDBC: 'jdbc:postgresql://192.168.15.103:5432/auth'
  DB_DATABASE: auth
  RABBIT_HOST: '192.168.15.103'
  RABBIT_USER: ${RABBIT_USER_ENV}
  RABBIT_PASSWORD: ${RABBIT_PWD_ENV}
  LOG_LEVEL: INFO
  
