apiVersion: v1
kind: ConfigMap
metadata:
  namespace: feriaz-app-env
  name: communication-configmap
data:  
  PORT: '8080'
  PROFILE: prod
  DB_ADDR: '192.168.15.103'  
  DB_USER: ${POSTGRES_USER}
  DB_PASSWORD: ${POSTGRES_PASSWORD}
  DB_JDBC: 'jdbc:postgresql://192.168.15.103:5432/communication'
  DB_DATABASE: communication
  RABBIT_HOST: '192.168.15.103'
  RABBIT_USER: ${RABBIT_USER_ENV}
  RABBIT_PASSWORD: ${RABBIT_PWD_ENV}
  EMAIL_USERNAME: ${EMAIL_USER_ENV} 
  EMAIL_PASSWORD: ${EMAIL_PWD_ENV} 