apiVersion: v1
kind: ConfigMap
metadata:
  namespace: feriaz-auth-env
  name: keycloak-service-configmap
data:
  KC_DB: postgres
  KC_DB_USERNAME: ${POSTGRES_USER}
  KC_DB_PASSWORD: ${POSTGRES_PASSWORD}
  KC_DB_SCHEMA: public
  KC_DB_URL: 'jdbc:postgresql://192.168.15.103:5432/keycloakdb'
  KC_DB_URL_DATABASE: keycloakdb
  KC_DB_URL_HOST: '192.168.15.103' 
  KC_DB_URL_PORT: '5432'
  KC_TRANSACTION_XA_ENABLED: 'false'
  KC_METRICS_ENABLED: 'true'
  KC_HEALTH_ENABLED: 'true'
  KC_DB_POOL_INITIAL_SIZE: '10'
  KC_DB_POOL_MAX_SIZE: '350'
  KC_LOG_LEVEL: INFO
  
