apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  namespace: feriaz-auth-env
  name: keycloak-service-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: keycloak-application
  minReplicas: 1
  maxReplicas: 4
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 81
          
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 81
